const gate = document.getElementById("gate");
const app = document.getElementById("app");

const music = document.getElementById("music");
const musicButton = document.getElementById("musicButton");
const musicStatus = document.getElementById("musicStatus");
const musicAudio = document.getElementById("musicAudio");

const volumeSlider = document.getElementById("volumeSlider");
const volumeValue = document.getElementById("volumeValue");

/*
  Word-by-word side lyrics.
  `lyrics-data.js` is generated by align_lyrics.py from the actual MP3.
  Do not hand-edit this file for timings; re-run ALIGN_LYRICS.bat instead.
*/
const lyricCues = Array.isArray(window.LYRIC_CUES) ? window.LYRIC_CUES : [];

let lyricTimeline = [];
let lyricWordNodes = [];
let activeLyricLine = -2;
let activeLyricWord = -1;
let lyricsAnimationFrame = null;

/* Default music volume: 5% */
let currentVolume = 5;

musicAudio.volume = currentVolume / 100;
volumeSlider.value = currentVolume;
volumeValue.textContent = `${currentVolume}%`;

function splitWords(text) {
  return text.trim().split(/\s+/).filter(Boolean);
}

function getWordWeight(word) {
  const cleanWord = word.toLowerCase().replace(/[^a-z]/g, "");
  const vowelGroups = cleanWord.match(/[aeiouy]+/g);
  const syllables = Math.max(1, vowelGroups ? vowelGroups.length : 1);

  /* Slight extra time for longer words such as "Loverman" and "waiting". */
  return syllables + Math.min(cleanWord.length / 15, 0.42);
}

function buildWords(text, start, sungDuration) {
  const words = splitWords(text);
  const weights = words.map(getWordWeight);
  const totalWeight = weights.reduce((sum, weight) => sum + weight, 0);
  let cursor = start;

  return words.map((word, index) => {
    const wordCue = { text: word, start: cursor };
    cursor += (weights[index] / totalWeight) * sungDuration;
    return wordCue;
  });
}

function buildLyricTimeline(force = false) {
  if (!force && lyricTimeline.length) {
    return;
  }

  lyricTimeline = lyricCues
    .filter((cue) => cue && cue.text && Number.isFinite(Number(cue.start)))
    .map((cue) => {
      const cueStart = Number(cue.start);
      const cueEnd = Number(cue.end);
      const hasAlignedWords = Array.isArray(cue.words) && cue.words.length > 0;
      const words = hasAlignedWords
        ? cue.words
            .filter((word) => word && word.text && Number.isFinite(Number(word.start)))
            .map((word) => ({
              text: word.text,
              start: Number(word.start),
              end: Number.isFinite(Number(word.end))
                ? Number(word.end)
                : Number(word.start) + 0.12
            }))
        : buildWords(
            cue.text,
            cueStart,
            Math.max(0.2, (Number.isFinite(cueEnd) ? cueEnd : cueStart + 2) - cueStart)
          );

      return {
        section: cue.section || "LYRICS",
        text: cue.text,
        start: words[0] ? words[0].start : cueStart,
        end: words.length
          ? words[words.length - 1].end
          : (Number.isFinite(cueEnd) ? cueEnd : cueStart + 2),
        words
      };
    });

  activeLyricLine = -2;
  activeLyricWord = -1;
}

function getLyricLineIndex(time) {
  let index = -1;

  lyricTimeline.forEach((line, lineIndex) => {
    if (time >= line.start) {
      index = lineIndex;
    }
  });

  return index;
}

function getLyricWordIndex(line, time) {
  let index = 0;

  line.words.forEach((word, wordIndex) => {
    if (time >= word.start) {
      index = wordIndex;
    }
  });

  return index;
}

function renderWaitingState() {
  lyricsSection.textContent = "TABZ LOVERMAN";
  lyricsLine.textContent = "...";
  lyricsNext.textContent = lyricTimeline[0]
    ? lyricTimeline[0].text
    : "Run ALIGN_LYRICS.bat once to generate vocal timings.";
  lyricWordNodes = [];
}

function renderLyricLine(lineIndex) {
  const line = lyricTimeline[lineIndex];
  const nextLine = lyricTimeline[lineIndex + 1];

  lyricsSection.textContent = line.section;
  lyricsNext.textContent = nextLine ? nextLine.text : "♥ End of the night ♥";
  lyricsLine.innerHTML = "";

  const fragment = document.createDocumentFragment();

  line.words.forEach((word, wordIndex) => {
    const wordElement = document.createElement("span");

    wordElement.className = "lyric-word";
    wordElement.dataset.wordIndex = wordIndex;
    wordElement.textContent = word.text;

    fragment.appendChild(wordElement);
  });

  lyricsLine.appendChild(fragment);
  lyricWordNodes = Array.from(lyricsLine.querySelectorAll(".lyric-word"));
}

function popWord(wordElement) {
  wordElement.classList.remove("pop");
  void wordElement.offsetWidth;
  wordElement.classList.add("pop");
}

function setLyricWordState(wordIndex, shouldPop = true) {
  lyricWordNodes.forEach((wordElement, index) => {
    const wasActive = wordElement.classList.contains("active");
    const isActive = index === wordIndex;

    wordElement.classList.toggle("revealed", index <= wordIndex);
    wordElement.classList.toggle("active", isActive);

    if (isActive && shouldPop && !wasActive) {
      popWord(wordElement);
    }
  });
}

function updateLyricProgress() {
  const duration = Number(musicAudio.duration);
  const currentTime = Number.isFinite(musicAudio.currentTime)
    ? musicAudio.currentTime
    : 0;
  const progress = Number.isFinite(duration) && duration > 0
    ? Math.max(0, Math.min(100, (currentTime / duration) * 100))
    : 0;

  lyricsProgress.style.width = `${progress}%`;

  if (!musicAudio.paused) {
    lyricsMode.textContent = `VOCAL SYNC · ${Math.round(progress)}%`;
  }
}

function syncLyrics(force = false) {
  buildLyricTimeline();

  if (!lyricTimeline.length) {
    lyricsMode.textContent = "RUN ALIGN_LYRICS.BAT";
    renderWaitingState();
    return;
  }

  const currentTime = Number.isFinite(musicAudio.currentTime)
    ? musicAudio.currentTime
    : 0;
  const nextLineIndex = getLyricLineIndex(currentTime);

  updateLyricProgress();

  if (nextLineIndex < 0) {
    if (force || activeLyricLine !== -1) {
      activeLyricLine = -1;
      activeLyricWord = -1;
      renderWaitingState();
    }

    return;
  }

  const lineChanged = nextLineIndex !== activeLyricLine;

  if (force || lineChanged) {
    activeLyricLine = nextLineIndex;
    activeLyricWord = -1;
    renderLyricLine(activeLyricLine);
  }

  const line = lyricTimeline[activeLyricLine];
  const nextWordIndex = getLyricWordIndex(line, currentTime);
  const wordChanged = nextWordIndex !== activeLyricWord;

  if (force || wordChanged || lineChanged) {
    activeLyricWord = nextWordIndex;
    setLyricWordState(activeLyricWord, wordChanged || lineChanged);
  }
}

function lyricsAnimationLoop() {
  syncLyrics();

  if (!musicAudio.paused && !musicAudio.ended) {
    lyricsAnimationFrame = requestAnimationFrame(lyricsAnimationLoop);
  }
}

function startLyricsAnimation() {
  cancelAnimationFrame(lyricsAnimationFrame);
  lyricsAnimationFrame = requestAnimationFrame(lyricsAnimationLoop);
}

function stopLyricsAnimation() {
  cancelAnimationFrame(lyricsAnimationFrame);
  lyricsAnimationFrame = null;
}

function updateLyricsBox(isPlaying, customLabel = "") {
  lyricsBox.classList.add("show");
  lyricsBox.classList.toggle("is-playing", isPlaying);

  if (customLabel) {
    lyricsMode.textContent = customLabel;
    return;
  }

  if (!isPlaying) {
    lyricsMode.textContent = "LYRICS PAUSED";
  }
}

function updateMusicUI(isPlaying, customStatus = "") {
  music.classList.toggle("playing", isPlaying);

  musicButton.setAttribute(
    "aria-label",
    isPlaying ? "Pause music" : "Play music"
  );

  if (customStatus) {
    musicStatus.textContent = customStatus;
    return;
  }

  musicStatus.textContent = isPlaying
    ? `LOVE MODE · ${currentVolume}%`
    : `PAUSED · ${currentVolume}%`;
}

function setVolume(value) {
  currentVolume = Number(value);

  musicAudio.volume = currentVolume / 100;
  volumeSlider.value = currentVolume;
  volumeValue.textContent = `${currentVolume}%`;

  musicStatus.textContent = !musicAudio.paused
    ? `LOVE MODE · ${currentVolume}%`
    : `PAUSED · ${currentVolume}%`;
}

async function startMusic() {
  try {
    await musicAudio.play();
    updateMusicUI(true);
    updateLyricsBox(true);
  } catch (error) {
    console.warn("Music could not start:", error);
    updateMusicUI(false, "TAP PLAY · 5%");
    updateLyricsBox(false, "TAP PLAY");
  }
}

function unlock() {
  if (gate.classList.contains("hide")) {
    return;
  }

  app.setAttribute("aria-hidden", "false");
  document.body.classList.remove("locked");
  gate.classList.add("hide");

  buildLyricTimeline(true);
  syncLyrics(true);
  updateLyricsBox(
    false,
    lyricTimeline.length ? "VOCAL SYNC READY" : "RUN ALIGN_LYRICS.BAT"
  );
  startMusic();
}

gate.addEventListener("click", unlock);

gate.addEventListener("keydown", (event) => {
  if (event.key === "Enter" || event.key === " ") {
    event.preventDefault();
    unlock();
  }
});

musicButton.addEventListener("click", async () => {
  if (musicAudio.paused) {
    await startMusic();
  } else {
    musicAudio.pause();
  }
});

volumeSlider.addEventListener("input", (event) => {
  setVolume(event.target.value);
});

musicAudio.addEventListener("loadedmetadata", () => {
  buildLyricTimeline(true);
  syncLyrics(true);
});

musicAudio.addEventListener("play", () => {
  updateMusicUI(true);
  updateLyricsBox(true);
  syncLyrics(true);
  startLyricsAnimation();
});

musicAudio.addEventListener("pause", () => {
  updateMusicUI(false);
  updateLyricsBox(false);
  stopLyricsAnimation();
});

musicAudio.addEventListener("seeked", () => {
  syncLyrics(true);
});

musicAudio.addEventListener("error", () => {
  console.error("Could not find the music file.");
  updateMusicUI(false, "AUDIO FILE MISSING");
  updateLyricsBox(false, "AUDIO ERROR");
  stopLyricsAnimation();
});

document.getElementById("year").textContent = new Date().getFullYear();

const reveals = document.querySelectorAll(".reveal");

const observer = new IntersectionObserver(
  (entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add("show");
        observer.unobserve(entry.target);
      }
    });
  },
  { threshold: 0.12 }
);

reveals.forEach((element) => observer.observe(element));

window.addEventListener(
  "pointermove",
  (event) => {
    document.documentElement.style.setProperty("--mx", `${event.clientX}px`);
    document.documentElement.style.setProperty("--my", `${event.clientY}px`);
  },
  { passive: true }
);

const canvas = document.getElementById("heartCanvas");
const ctx = canvas.getContext("2d");

let width = 0;
let height = 0;
let dpr = 1;
let hearts = [];
let sparkles = [];

function random(min, max) {
  return Math.random() * (max - min) + min;
}

function setupCanvas() {
  width = window.innerWidth;
  height = window.innerHeight;
  dpr = Math.min(window.devicePixelRatio || 1, 2);

  canvas.width = width * dpr;
  canvas.height = height * dpr;
  canvas.style.width = `${width}px`;
  canvas.style.height = `${height}px`;

  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

  const heartCount = Math.min(
    48,
    Math.max(22, Math.floor((width * height) / 38000))
  );

  hearts = Array.from({ length: heartCount }, () => ({
    x: random(0, width),
    y: random(0, height),
    size: random(3, 11),
    speed: random(0.08, 0.34),
    alpha: random(0.08, 0.34),
    angle: random(-0.6, 0.6),
    spin: random(-0.0018, 0.0018),
    phase: random(0, Math.PI * 2)
  }));

  const sparkleCount = Math.min(
    60,
    Math.max(25, Math.floor((width * height) / 27000))
  );

  sparkles = Array.from({ length: sparkleCount }, () => ({
    x: random(0, width),
    y: random(0, height),
    size: random(0.5, 1.8),
    alpha: random(0.08, 0.35),
    phase: random(0, Math.PI * 2)
  }));
}

function drawHeart(x, y, size, alpha, angle) {
  ctx.save();
  ctx.translate(x, y);
  ctx.rotate(angle);

  ctx.beginPath();
  ctx.moveTo(0, size * 0.35);

  ctx.bezierCurveTo(
    -size * 1.3,
    -size * 0.45,
    -size * 0.95,
    -size * 1.25,
    0,
    -size * 0.45
  );

  ctx.bezierCurveTo(
    size * 0.95,
    -size * 1.25,
    size * 1.3,
    -size * 0.45,
    0,
    size * 0.35
  );

  ctx.closePath();
  ctx.fillStyle = `rgba(255, 132, 172, ${alpha})`;
  ctx.fill();

  ctx.restore();
}

function draw(time = 0) {
  ctx.clearRect(0, 0, width, height);

  sparkles.forEach((sparkle) => {
    const flicker = 0.45 + 0.55 * Math.sin(time * 0.0013 + sparkle.phase);

    ctx.beginPath();
    ctx.arc(
      sparkle.x,
      sparkle.y,
      sparkle.size * flicker,
      0,
      Math.PI * 2
    );

    ctx.fillStyle = `rgba(255, 218, 228, ${sparkle.alpha * flicker})`;
    ctx.fill();
  });

  hearts.forEach((item) => {
    item.y -= item.speed;
    item.x += Math.sin(time * 0.0006 + item.phase) * 0.22;
    item.angle += item.spin;

    if (item.y < -30) {
      item.y = height + 30;
      item.x = random(0, width);
    }

    drawHeart(item.x, item.y, item.size, item.alpha, item.angle);
  });

  requestAnimationFrame(draw);
}

window.addEventListener("resize", setupCanvas, { passive: true });

buildLyricTimeline(true);
syncLyrics(true);
setupCanvas();
draw();
